### PR TITLE
Added index for internal_status

### PR DESCRIPTION
**Pull request by mikoczy**

### CODE REVIEW

**Comment by rootpd** [comment]
I know why you submit this (I saw the slow query); but did you test if that actually helps? From what I know, columns with enum values (in our case 3 different values) can't really utilize the index effectively and end up with full table scan anyway.

I'm worried this will only take disk space and slows down inserts.

**Comment by mikoczy** [comment]
yes, but only on a local environment... it managed to reduce query execution time from nearly a second to 0.001.. according to `explain`, the index is used..

**Comment by rootpd** [comment]
In our case, the original query runs for ~1 second, the index makes it a bit faster, but not 0.001 fast. I'll merge it, but it probably won't do any miracles:

image

**Comment by rootpd** [comment]
Meh, this was merged in November 2021, closing up.

**Pull request closed without merging**
