### PR TITLE
Created article view count based subscription type. Added migration. …

### PR DESCRIPTION
**Pull request by l-besenyei**
Subscription table has been extended with a field named 'articles', this will store data about the articles the free subscriber has viewed.
A new length method has been created so a new free subscription can be created that will allow access to set number of articles based on the existing length field of a subscription type.
A new content access has been created named 'article count' to distinguish subscription type from regular subscription.
SubscriptionFormFactory class has been extended with an 'article' textarea, so administrators can view the articles a free subscriber has viewed, and edit them if necessary.
A new API callback (/article/view) has been added to count the articles the free subscribers access, or not, if the user exceeded the number of free articles to view.

### CODE REVIEW

**Comment by rootpd** [comment]
This is a good idea, but it seems like it should rather be completely new module, not an extension to subscriptions module, as it's not fundamentally adding anything directly to the subscriptions.

You can create your own module supporting this feature and attach to the CRM via extension points you used here in this MR - API handler, ArticleCountLengthMethod, DB migration (I recommend separate table instead of adding column to `subscriptions` table). The feature itself isn't generic enough to be included directly within subscription module and would be better of as a separate module.

If there's something you'd be missing directly in subscriptions module in order to attach the implementation from your own module, let us know and we could include that.

**Comment by lulco** [comment]
Hellou @rootpd, we would like to extend SubscriptionFormFactory but it is an anonymous service, is it possible to add some name to this service? (Ideally name all services). We can prepare pull request if it would be accepted.

**Comment by rootpd** [comment]
@lulco We probably can, but it's not very safe in regard of future changes of that form - any breaking change would be documented, but it would be an extra work for you.

There's a way how to extend a form with your fields from your own module - via data providers. For example user registration form in admin by default works only with fields users-module is aware of. But invoices-module can inject its own fields into that form:

- [This is the user form to register users in admin](https://github.com/remp2020/crm-users-module/blob/master/src/forms/UserFormFactory.php). See line 95 where the data providers are trigerred.
- [This is the implementation of data provider](https://github.com/remp2020/crm-invoices-module/blob/master/src/dataproviders/UserFormDataProvider.php) adding extra fields to the form and also handling the submitted form with its own logic.

That way you could extend any form. Not all of them have data provider injection points, so we could add ones that you need. But if this is not enough, you could go with path of extending the form yourself once we add names to the services.

(PR will be accepted if you have time for it)

**Comment by lulco** [comment]
OK, thank you for now, we found out how to override service without the name :)

**Comment by rootpd** [comment]
@l-besenyei Hi Levente (just saw you commited some more changes here). As I [mentioned earlier](https://github.com/remp2020/crm-subscriptions-module/pull/3#issuecomment-582857517), this will be probably better off as a separate module/extension you can create within your application (crm-skeleton you've checked out).

**Pull request closed without merging**
